networks:
  bar-dev:
    driver: bridge

services:
  bar:
    image: bar
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    build:
      context: .
      dockerfile: Api/Dockerfile
    networks:
      - bar-dev
    depends_on:
      - postgres
             
  postgres:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "bar"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5433:5432"
    networks:
      - bar-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: